export { default as Page1 } from './page-1'
export { default as Page2 } from './page-2'
export { default as Page3 } from './page-3'
export { default as ContentLandingPage } from './content-landingpage'
export { default as ContentChatBox } from './content-chatbox'
export { default as ContentTabPages } from './content-tabpages'
export { default as ContentAuth } from './content-auth'
